### ISSUE TITLE
Сверстать список "сервисы"

### ISSUE THREAD

**Issue by AndreiGubskii** [AndreiGubskii/html_group_8_teamwork_team_5#11]
**1. Задача**
- Сверстать [список](http://c2n.me/3ImI5tb) 
- Список должен совпадать с макетом и выглядеть аккуратно на экранах от 320px 

**2. Реализация:**
- Про списки можно посмотреть [тут](https://webref.ru/layout/learn-html-css/creating-lists)

**3. Тестирование:**
- Список соответствует дизайну (pixel perfect)
- Список не ломается при изменении ширины браузера 

**4.Время:**
Время по плану: 30 минут
Время по факту: 30 минут

**Comment by thebaurak** [comment]
Сделано.
