### ISSUE TITLE
Собрать форму и карту в один блок

### ISSUE THREAD

**Issue by AndreiGubskii** [AndreiGubskii/html_group_8_teamwork_team_5#15]
**1. Задача** 

- Собрать блок  из заранее сверстанных отдельных блоков

- Блок  должен быть адаптивным: При сжатии окна браузера на 768px форма должна находиться вверху страницы а карта отображаться под ней. При сжатии окна до 320px форма и карта должны растягиваться на 100% экрана браузера.

- При растягивании окна браузера свыше 768px карта должна занимать весь контейнер а форма отображаться в верхнем правом углу поверх карты как в [макете](http://c2n.me/3ImP0Ev)

**2. Реализация**
- Макет contact.psd можно взять [тут](https://drive.google.com/drive/folders/0B_UCljvTCPnlWU1PTFItVWJRd2s)
- Блоки для страницы лежат в корне проекта в папке [tech](https://github.com/AndreiGubskii/html_group_8_teamwork_team_5/tree/master/tech)

**3. Тестирование**
- Результат максимально схож с макетом (для desctop версии)
- Страница выглядит аккуратно на всех экранах от 320px
- При ширине браузера 768px и менее форма находится вверху страницы а карта снизу

**4. Время**
Запланировано: 2 часа
По факту: 2 часа

**Comment by moskit33** [comment]
Сделано
