### ISSUE TITLE
Cлайдер для Singlepost и Singlework

### ISSUE THREAD

**Issue by moskit33** [AndreiGubskii/html_group_8_teamwork_team_5#17]
**1. Задача**
- Необходимо сверстать [блок-слайдер с информацией](http://prntscr.com/ekbhls).
- Картинки в слайдере должны быть кликабельны и являться ссылкой 
- Блок должен соответствовать макету и корректно отображаться на mobile и desktop устройствах

**2. Реализация:**
- [Блок-слайдер с информацией](http://prntscr.com/ekbhls) используется на нескольких страницах в проекте поэтому необходимо сверстать его по принципу модульной верстки 
- Использовать [slick-слайдер](http://kenwheeler.github.io/slick), а также слайдер требуется [кастомизировать](http://prntscr.com/ekbnn6). Slick-slider находится в папке vendor, нужно подключить к проекту. 

**3. Тестирование:**

- [Блок](http://prntscr.com/ekbhls) не ломается и выглядит аккуратно на экранах от 320px и более  

- [Блок](http://prntscr.com/ekbhls) соответствует дизайну (pixel perfect)

**4.Время:**

Время по плану: 2 часа
Время по факту:

**Comment by AndreiGubskii** [comment]
Сверстал секцию с информацией, встроил слайдер, осталось кастомизировать точки слайдера.
