### ISSUE TITLE
Блок архив

### ISSUE THREAD

**Issue by moskit33** [AndreiGubskii/html_group_8_teamwork_team_5#19]
**1. Задача**
- Необходимо сверстать [блок-архив](http://prntscr.com/ekcci5).
- Месяцы в архиве должны быть кликабельны 
- Блок должен соответствовать макету и корректно отображаться на mobile и desktop устройствах

**2. Реализация:**
- [Блок-слайдер с информацией](http://prntscr.com/ekcci5) используется на одной странице так что [просто сделайте это](https://www.youtube.com/watch?v=ZXsQAXx_ao0).

**3. Тестирование:**

- [Блок](http://prntscr.com/ekcci5) не ломается и выглядит аккуратно на экранах от 320px и более  

- [Блок](http://prntscr.com/ekcci5) соответствует дизайну (pixel perfect)

**4.Время:**

Время по плану: 0.5 часа
Время по факту: 0.5 часа

**Comment by thebaurak** [comment]
Архиве сверстан, месяца кликабельны, перфект пиксель.
