### ISSUE TITLE
Home Page Gallery Block

### ISSUE THREAD

**Issue by thebaurak** [AndreiGubskii/html_group_8_teamwork_team_5#2]
- <h3>Задача</h3>

<p>Сверстать секцию галереи на главной странице.(home page) </p> 

<https://drive.google.com/drive/folders/0B_UCljvTCPnlWU1PTFItVWJRd2s>

- <h3>Требования</h3>

<p>Галерея должна совпадать с дизайном, пиксель перфект (не доводите до фанатизма, в рамках разумного)</p>
<p>При наведении на изображение галереи появляется информация о нем с анимацией (любая анимация)</p>
<p>Grid система галереи может быть сделана на bootsrap, bootstrap - простота (быстрота), валидность, понятный код в котором легко разобраться.</p>

- <h3>Тестирование</h3>
<p>Протестировать макет на адаптивность на mobile версии примерно (320px) блоки должны будут выстроится друг за другом. На table версии (для планшетов, примерно 750px) блоки  выстраиваются по два. На десктоп версии блоки показаны на макете. Не должно быть скролла на странице.</p>

- <h3>Макет</h3>

<https://drive.google.com/drive/folders/0B_UCljvTCPnlWU1PTFItVWJRd2s/>

- <h3>Время</h3>

По плану: 4 часа.
По факту:  5 часов.

**Comment by moskit33** [comment]
Добавил адаптивные блоки, без блока с информацией и анимации. Добавил fontawesome в css файл главный и в папку fonts главную
