### ISSUE TITLE
Блок с готовыми проектами

### ISSUE THREAD

**Issue by moskit33** [AndreiGubskii/html_group_8_teamwork_team_5#20]
**1. Задача**
- Необходимо сверстать [с готовыми проектами](http://prntscr.com/ekci72) singlework.psd.
- Картинки должны быть кликабельны и являться ссылкой, можно навесить анимации.
- Блок должен соответствовать макету и корректно отображаться на mobile и desktop устройствах

**2. Реализация:**
- [Блок с готовыми проектами](http://prntscr.com/ekci72) будет использоваться только в singlework.html так что [просто сделайте это](https://www.youtube.com/watch?v=ZXsQAXx_ao0). 
- Можно использовать bootstrap колонки. На desktop по три картинки, на mobile и tablet по одной картинке

**3. Тестирование:**

- [Блок](http://prntscr.com/ekci72) не ломается и выглядит аккуратно на экранах от 320px и более  

- [Блок](http://prntscr.com/ekci72) соответствует дизайну (pixel perfect)

**4.Время:**

Время по плану: 1 час
Время по факту: 30 минут.

**Comment by thebaurak** [comment]
Блок с готовыми проектами сверстан, картинки кликабельны, навесил анимации как в задании #2.
Совпадает с дизайном макета использовал колонки бустрапа, На desktop по три картинки, на mobile и table по одной картинке.
