### ISSUE TITLE
Блок галерея наших работ

### ISSUE THREAD

**Issue by moskit33** [AndreiGubskii/html_group_8_teamwork_team_5#21]
**1. Задача**
- Необходимо сверстать [блок с галереей наших работ](http://prntscr.com/ekcyba) singlepost.psd.
- Картинки должны быть кликабельны и являться ссылкой.
- Блок должен соответствовать макету и корректно отображаться на mobile и desktop устройствах

**2. Реализация:**
- [Блок с готовыми проектами](http://prntscr.com/ekcyba) будет использоваться только в singlepost.html так что [просто сделайте это](https://www.youtube.com/watch?v=ZXsQAXx_ao0). 
- Можно использовать bootstrap колонки. На desktop по 8 картинок, на tablet по 4 картинок, на mobile по 4 картинки

**3. Тестирование:**

- [Блок](http://prntscr.com/ekcyba) не ломается и выглядит аккуратно на экранах от 320px и более  

- [Блок](http://prntscr.com/ekcyba) соответствует дизайну (pixel perfect)

**4.Время:**

Время по плану: 1 час
Время по факту: 1 час

**Comment by thebaurak** [comment]
Блок с галлерей наших работ сверстан, соответствует дизайну, колонки отображаются корректно.
