### ISSUE TITLE
Блок Features

### ISSUE THREAD

**Issue by moskit33** [AndreiGubskii/html_group_8_teamwork_team_5#22]
**1. Задача**
- Необходимо сверстать [блок-features](http://prntscr.com/ekd3lr) singlework.psd .
- Содержимое в списке должны быть кликабельны 
- Блок должен соответствовать макету и корректно отображаться на mobile и desktop устройствах

**2. Реализация:**
- [Блок-слайдер с информацией](http://prntscr.com/ekd3lr) используется на одной странице так что [просто сделайте это](https://www.youtube.com/watch?v=ZXsQAXx_ao0).
- fa fa-check для иконок списка
**3. Тестирование:**

- [Блок](http://prntscr.com/ekd3lr) не ломается и выглядит аккуратно на экранах от 320px и более  

- [Блок](http://prntscr.com/ekd3lr) соответствует дизайну (pixel perfect)

**4.Время:**

Время по плану: 0.3 часа
Время по факту: 0.3 часа

**Comment by thebaurak** [comment]
блок features singlework.psd . сверстан, соответствует дизайну, содержимое в списке кликабельно.
