### ISSUE TITLE
Блок с видео, блок слайдер. blog.psd

### ISSUE THREAD

**Issue by thebaurak** [AndreiGubskii/html_group_8_teamwork_team_5#23]
**<h2>1. Задача№1</h3>**
- Cверстать  [блок с видео](http://clip2net.com/s/3IBvug2).
- В блоке должен быть видео раздел, с разрешением в 294х184 и разметка.
 [Здесь](http://htmlbook.ru/html/video) можно прочитать как реализовать этот блок.
- Блок должен соответствовать макету и корректно отображаться на mobile и desktop устройствах
[Иконка 1(комментарий)](http://fontawesome.io/icon/comment/).
[Иконка 2(календарь)](http://fontawesome.io/icon/calendar/).

**<h2>1.1. Задача№2</h3>**
- Cверстать  [блок слайдер](http://clip2net.com/s/3IBvOlN).
- В блоке должен быть слайдер и разметка.
- Блок должен соответствовать макету и корректно отображаться на mobile и desktop устройствах

**<h3>2. Тестирование:</h3>**
- Блоки  не ломается и выглядит аккуратно на экранах от 320px и более  
- Блоки  соответствует дизайну (pixel perfect)

**<h3>3.Время:</h3>**
 Время: 2 часа
 Время по факту:

**Comment by moskit33** [comment]
В 71 коммите добавил видео-блок и слайдер-блок, но столкнулся с проблемой подключения слайдера и его кастомизации.

**Comment by thebaurak** [comment]
В чате, я описал как тебе действовать, удачи.

**Comment by moskit33** [comment]
FINISH!
