### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by thebaurak** [AndreiGubskii/html_group_8_teamwork_team_5#3]
- <h3>Задача</h3>

<p>Сверстать адаптивное меню на descktop и mobile версию</p>

- <h3>Требования</h3>

<p>При нажатии на ссылку в меню, должно переносить в выбранный раздел. Меню должно быть полностью адаптивным, на мобайле появляется гамбургер при нажатии на который появляется меню слева на права, меню должно совпадать с макетом. Меню имеет ховер эффект на каждой li, а так же ниже в списке с Filter</p> 

<http://prnt.sc/ehwzd2>

- <h3>Критерий готовности</h3>

<p>Меню не ломается при ресайзе менюшки. </p>

- <h3>Макет</h3>

<https://drive.google.com/drive/folders/0B_UCljvTCPnlWU1PTFItVWJRd2s\>

- <h3>Время</h3>
 по плану:  4 часа
по факту:  4 часа на верстку
+1 час потратил на изучение mobile jq для реализации свайпов

**Comment by AndreiGubskii** [comment]
Сделал Desctop верстку.

**Comment by AndreiGubskii** [comment]
Сверстал меню. На мобильной версии появляется шапка с логотипом и кнопкой меню. При нажатии на кнопку, меню плавно появляется слева на право, и при повторном нажатии на кнопку, скрывается справа налево. Так же меню можно открыть по свайпу вправо и закрыть по свайпу влево. На desctop версии шапка прилипает к меню сверху. Меню все время активно и находится с левой стороны.
