### ISSUE TITLE
Сборка и тестирование первого спринта.

### ISSUE THREAD

**Issue by thebaurak** [AndreiGubskii/html_group_8_teamwork_team_5#4]
- <h3>Задача</h3>
 <p>Собрать три элемента  первого спринта в одну структуру (buttons, menu, gallery block), структура должна быть адаптивная, и совпадать с макетом</p>

- <h3>Тестирование</h3>
 <p>Протестировать собранную страницу, выявить и устранить ошибки если таковы имеются</p>

- <h3>Время</h3>
по плану: 2 часа
по факту:

**Comment by AndreiGubskii** [comment]
Сделано!
