### ISSUE TITLE
Сверстать блок с тэгами

### ISSUE THREAD

**Issue by AndreiGubskii** [AndreiGubskii/html_group_8_teamwork_team_5#6]
**1. Задача**
- Необходимо сверстать [блок тегов](http://c2n.me/3Im3mio).
- Каждый отдельный тэг должен быть ссылкой
- Блок должен соответствовать макету и корректно отображаться на mobile и desctop устройствах

**2. Реализация:**
- [Блок тегов](http://c2n.me/3Im3mio) используется на нескольких страницах в проекте поэтому необходимо сверстать его по принципу модульной верстки 

**3. Тестирование:**

- [Блок](http://c2n.me/3Im3mio) не ломается и выглядит аккуратно на экранах от 320px и более  

- [Блок](http://c2n.me/3Im3mio) соответствует дизайну (pixel perfect)

**4.Время:**
Время по плану: 1 час
Время по факту: 30 минут

**Comment by thebaurak** [comment]
Сверстал блок тегов, каждый блок является ссылкой, соответствие с дизайном.
