### ISSUE TITLE
Свестать блок с информацией о посте

### ISSUE THREAD

**Issue by AndreiGubskii** [AndreiGubskii/html_group_8_teamwork_team_5#7]
**1. Задача**
- Необходимо сверстать [блок с информацией о посте](http://clip2net.com/s/3ImmZxW).
- Каждый отдельный пункт должен быть ссылкой
- Блок должен соответствовать макету и корректно отображаться на mobile и desctop устройствах

**2. Реализация:**
- [Блок с информацией о посте](http://clip2net.com/s/3ImmZxW) используется на нескольких страницах в проекте поэтому необходимо сверстать его по принципу модульной верстки 
- Иконки можно взять из [font-awesome](http://fontawesome.io/)
       - [fa-user](http://fontawesome.io/icon/user/)
       - [fa-heart](http://fontawesome.io/icon/heart/)
       - [fa-calendar](http://fontawesome.io/icon/calendar/)
       - [fa-comment](http://fontawesome.io/icon/comment/)

**3. Тестирование:**

- [Блок](http://clip2net.com/s/3ImmZxW) не ломается и выглядит аккуратно на экранах от 320px и более  

- [Блок](http://clip2net.com/s/3ImmZxW) соответствует дизайну (pixel perfect)

**4.Время:**

Время по плану: 1 час
Время по факту: 30 минут

**Comment by thebaurak** [comment]
Блок с информацией о посте сверстан. Каждый отдельный пункт является ссылкой, полностью соответствует дизайну.
