### ISSUE TITLE
Сверстать блок "наш коллектив"

### ISSUE THREAD

**Issue by AndreiGubskii** [AndreiGubskii/html_group_8_teamwork_team_5#9]
**1. Предыстория**
Заказчик хочет видеть на странице "О нас" блок с коллективом компании. В блоке должны располагаться фото сотрудников. По наведению курсора мыши на эти фото или по событию active должна отображаться информация о данном сотруднике как показано на [макете](http://c2n.me/3Imzoof)

**2. Задача**

1.  Сверстать элемент в котором будет находится фото сотрудника

      - Элемент должен растягиваться на 100% по ширине колонки в которой он находится 
      - При наведении курсора, а так же по клику на этот элемент (с фотографией сотрудника)  должна появляться информация поверх этого элемента. Пример [тут](http://c2n.me/3Imzoof)
      - Анимацию появления лучше всего использовать как в задании #2. т.к важно сохранить единую стилистику проекта.

2. Сверстать сетку блока "Наш коллектив" 
     - Сетку лучше всего реализовать на bootstrap'e т.к в проекте используется именно этот подход. 
     - Сетка должна тянуться на весь блок и адаптивна под mobile устройства

**3. Реализация:**
- **Важно!** Учесть стили из задачи #2. Перед началом реализации данной задачи стоит изучить 
[main.css](https://github.com/AndreiGubskii/html_group_8_teamwork_team_5/blob/master/css/main.css) после комментария  "Home page" 

**4. Тестирование:** 
-  [Блок](http://c2n.me/3Imzoof) соответствует дизайну (pixel perfect)
-  [Блок](http://c2n.me/3Imzoof) не ломается при изменении ширины окна браузера

**5.Время:**

Время по плану: 1 час 30 минут
Время по факту: 1 час 30 минут

**Comment by thebaurak** [comment]
Сделал, учел все стили, навесил такую же анимацию как в задании #2 . Сетка реализол на бутстрапе.
